name: Hello
on:
    repository_dispatch:
    types: [triggerCI]
jobs:

  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app && /usr/bin/xcodebuild -version
    - name: Pod De Integrate
      run: pod deintegrate
    - name: Pod Run
      run: pod update
    - name: Run unit tests
      run: xcodebuild test -scheme Integrate\ CICD -workspace Integrate\ CICD.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' | xcpretty && exit ${PIPESTATUS[0]}

        
