name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
jobs:

  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: |
      pod deintegrate \
      pod update \
      xcodebuild test -scheme Integrate\ CICD -workspace Integrate\ CICD.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' | xcpretty && exit ${PIPESTATUS[0]}

        
