name: Deploy
on:
   workflow_dispatch:
     inputs:
       flavour:
         description: 'Flavour'
         required: true
         default: 'A1 Mercado'
jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
