name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Pod De Integrate
      run: pod deintegrate
    - name: Pod Run
      run: pod update
    - name: Decrypt large secret
      run: ./.github/secrets/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PASSWORD }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild -sdk iphoneos -workspace Integrate\ CICD.xcworkspace -configuration Release -scheme Integrate\ CICD -derivedDataPath DerivedData -archivePath DerivedData/Archive/Integrate\ CICD archive
